version: "3"
services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=typegraphql
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
